artnet: main.o config.o connection.o modus.o
	g++ -o artnet main.o config.o connection.o modus.o

main.o: main.cpp
	g++ -c main.cpp

config.o: config.cpp
	g++ -c config.cpp

connection.o: connection.cpp
	g++ -c connection.cpp

modus.o: modus.cpp
	g++ -c modus.cpp
